[deploy]
startCommand = "php artisan migrate --force; php artisan config:cache; php artisan storage:link; /start.sh"
healthcheckPath = "/health.php"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"

