[deploy]
startCommand = "php artisan migrate --force && php artisan config:cache && php artisan storage:link && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
healthcheckPath = "/loans/chat"
healthcheckTimeout = 120
restartPolicyType = "on_five_restarts_in_one_minute"

